
server:
  port: 8082
  servlet:
      context-path: /

druid:
  allow: #允许登陆的IP地址
    ip: localhost
  login: #登陆的账户密码
    user_name: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    super-mapper-class: com.rj.btp.framework.mapper.BaseMapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  path: ./logs
  level:
    org.thymeleaf: info

spring:
  mvc:
    static-path-pattern: /**
  resources:
      static-locations: classpath:/static/x-admin/
  thymeleaf:
      prefix: classpath:/static/x-admin/
      cache: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renjie02?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true

info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
    test: test

management:
  endpoints:
    web:
      exposure:
        include: heath,info,env,beans
    health:
      show-details: always
    shutdown:
      enabled: true

xxl:
  job:
    admin:
    ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.1.130:8081/xxl-job-admin
    executor:
    ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: btp-boot
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      ### xxl-job log path
      logpath: /Users/renjie/workspace/xxl-job/data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    accessToken: